<!DOCTYPE html>
<html>
<head>
    <title>Trinity Unit Test Report</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

<style>
body {
    font-family: Calibri, "Trebuchet MS", sans-serif;
}
* {
    word-break: break-all;
}
table, td, th, .dataid {
    border: 1px solid #aaa;
    border-collapse: collapse;
    background: #fff;
}
section {
    background: rgba(0, 0, 0, 0.05);
    margin: 2ex;
    padding: 1ex;
    border: 1px solid #999;
    border-radius: 5px;
}
h1 {
    font-size: 130%;
}
h2 {
    font-size: 120%;
}
h3 {
    font-size: 100%;
}
h4 {
    font-size: 85%;
}
h1, h2, h3, h4, a[href] {
    cursor: pointer;
    color: #0074d9;
    text-decoration: none;
}
h3 strong, a.failed {
    color: #ff4136;
}
.failed {
    color: #ff4136;
}
a.success {
    color: #3d9970;
}
pre {
    font-family: 'Consolas', 'Deja Vu Sans Mono',
                 'Bitstream Vera Sans Mono', 'Monaco',
                 'Courier New', monospace;
}

.test-details,
.traceback {
    display: none;
}
section:target .test-details {
    display: block;
}

</style>
</head>
<body>
    <h1>Trinity Automated Test Results</h1>
    <h2>2017-01-05 09:25</h2>
    <section>
        <table>
            <tr>
                <th>Class</th>
                <th class="failed">Fail</th>
                <th class="failed">Error</th>
                <th>Skip</th>
                <th>Success</th>
                <th>Total</th>
            </tr>
                <tr>
                    <td>sample_data_tests.TestTrinitySampleData</td>
                    <td class="failed">4</td>
                    <td>0</td>
                    <td>0</td>
                    <td>3</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>test_prep.TestTrinityPrepFlag</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>18</td>
                    <td>18</td>
                </tr>
                <tr>
                    <td>tests.TestTrinity</td>
                    <td class="failed">5</td>
                    <td class="failed">1</td>
                    <td>0</td>
                    <td>15</td>
                    <td>21</td>
                </tr>
            <tr>
                <td><strong>Total</strong></td>
                <td class="failed">9</td>
                <td class="failed">1</td>
                <td>0</td>
                <td>36</td>
                <td>46</td>
            </tr>
        </table>
    </section>
    <h1>Failure details</h1>
            <section>
                <h2>sample_data_tests.TestTrinitySampleData (4 failures, 0 errors)</h2>
                <div>
                        <section id="sample_data_tests.TestTrinitySampleData:test_DE_analysis_EdgeR">
                            <h3>test_DE_analysis_EdgeR: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/sample_data_tests.py", line 38, in test_DE_analysis_EdgeR
    self.assertTrue(os.path.isfile(check_file), 'DE output file not created')
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: DE output file not created
</pre>
                                <h4>Details</h4>
                                <pre>DE output file not created</pre>
                            </div>
                        </section>
                        <section id="sample_data_tests.TestTrinitySampleData:test_align_and_estimate_abundance">
                            <h3>test_align_and_estimate_abundance: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/sample_data_tests.py", line 45, in test_align_and_estimate_abundance
    self.assertTrue(os.path.isfile(check_file), 'RSEM-gene.counts.matrix not created')
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: RSEM-gene.counts.matrix not created
</pre>
                                <h4>Details</h4>
                                <pre>RSEM-gene.counts.matrix not created</pre>
                            </div>
                        </section>
                        <section id="sample_data_tests.TestTrinitySampleData:test_full_edgeR_pipeline">
                            <h3>test_full_edgeR_pipeline: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/sample_data_tests.py", line 49, in test_full_edgeR_pipeline
    self.assertTrue(os.path.isfile(check_file), 'edgeR sorted BAM not created')
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: edgeR sorted BAM not created
</pre>
                                <h4>Details</h4>
                                <pre>edgeR sorted BAM not created</pre>
                            </div>
                        </section>
                        <section id="sample_data_tests.TestTrinitySampleData:test_trinity_assembly">
                            <h3>test_trinity_assembly: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/sample_data_tests.py", line 34, in test_trinity_assembly
    self.assertTrue(100 <= seq_count <= 120, msg='Found %s sequences' % seq_count)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: Found 86 sequences
</pre>
                                <h4>Details</h4>
                                <pre>Found 86 sequences</pre>
                            </div>
                        </section>
                </div>
            </section>
            <section>
                <h2>tests.TestTrinity (5 failures, 1 errors)</h2>
                <div>
                        <section id="tests.TestTrinity:test_Inchworm_handles_compressed_files">
                            <h3>test_Inchworm_handles_compressed_files: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 145, in test_Inchworm_handles_compressed_files
    self.assertTrue(2850 <= num_lines <= 3100, msg='Found %s lines' % num_lines)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: Found 2739 lines
-------------------- >> begin captured stdout << ---------------------
A compressed single file should be handlred correctly by Inchworm
Command line: Trinity --max_memory 2G --seqType fq --single reads.left.fq.gz --SS_lib_type F --no_run_chrysalis

--------------------- >> end captured stdout << ----------------------
</pre>
                                <h4>Details</h4>
                                <pre>Found 2739 lines
-------------------- >> begin captured stdout << ---------------------
A compressed single file should be handlred correctly by Inchworm
Command line: Trinity --max_memory 2G --seqType fq --single reads.left.fq.gz --SS_lib_type F --no_run_chrysalis

--------------------- >> end captured stdout << ----------------------</pre>
                            </div>
                        </section>
                        <section id="tests.TestTrinity:test_QuantifyGraph_works">
                            <h3>test_QuantifyGraph_works: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 151, in test_QuantifyGraph_works
    self.assertEquals(0, result, "QuantifyGraph failed")
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 511, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 504, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: QuantifyGraph failed
</pre>
                                <h4>Details</h4>
                                <pre>QuantifyGraph failed</pre>
                            </div>
                        </section>
                        <section id="tests.TestTrinity:test_no_JM_specified_error">
                            <h3>test_no_JM_specified_error: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 186, in test_no_JM_specified_error
    self.assertTrue("Error, must specify max memory for jellyfish to use, eg.  --max_memory 10G" in error)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
max_memory flag is required

--------------------- >> end captured stdout << ----------------------
</pre>
                                <h4>Details</h4>
                                <pre>False is not true
-------------------- >> begin captured stdout << ---------------------
max_memory flag is required

--------------------- >> end captured stdout << ----------------------</pre>
                            </div>
                        </section>
                        <section id="tests.TestTrinity:test_scaffold_iworm_contigs">
                            <h3>test_scaffold_iworm_contigs: <strong>exceptions.OSError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 124, in test_scaffold_iworm_contigs
    f = subprocess.check_output([exe, bamfile, ifile]).split('\n')
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/subprocess.py", line 537, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------- >> begin captured stdout << ---------------------
scaffold_iworm_contigs works as expected

--------------------- >> end captured stdout << ----------------------
</pre>
                                <h4>Details</h4>
                                <pre>[Errno 2] No such file or directory
-------------------- >> begin captured stdout << ---------------------
scaffold_iworm_contigs works as expected

--------------------- >> end captured stdout << ----------------------</pre>
                            </div>
                        </section>
                        <section id="tests.TestTrinity:test_set_no_cleanup_and_full_cleanup_error">
                            <h3>test_set_no_cleanup_and_full_cleanup_error: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 196, in test_set_no_cleanup_and_full_cleanup_error
    self.assertTrue("cannot set --no_cleanup and --full_cleanup as they contradict" in error)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
Setting no_cleanup and full_cleanup together results in an error

--------------------- >> end captured stdout << ----------------------
</pre>
                                <h4>Details</h4>
                                <pre>False is not true
-------------------- >> begin captured stdout << ---------------------
Setting no_cleanup and full_cleanup together results in an error

--------------------- >> end captured stdout << ----------------------</pre>
                            </div>
                        </section>
                        <section id="tests.TestTrinity:test_version">
                            <h3>test_version: <strong>exceptions.AssertionError</strong></h3>
                            <div class="test-details">
                                <h4>Traceback</h4>
                                <pre class="traceback">Traceback (most recent call last):
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/N/dc2/projects/hpc/trinity/JenkinsTest/src/util/support_scripts/tests/tests.py", line 167, in test_version
    self.assertTrue('Trinity version: __TRINITY_VERSION_TAG__' in e.output)
  File "/N/soft/rhel6/python/2.7.3/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
Version flag should return version information

--------------------- >> end captured stdout << ----------------------
</pre>
                                <h4>Details</h4>
                                <pre>False is not true
-------------------- >> begin captured stdout << ---------------------
Version flag should return version information

--------------------- >> end captured stdout << ----------------------</pre>
                            </div>
                        </section>
                </div>
            </section>

    <h1>All tests</h1>
    <section>
        <h2>sample_data_tests.TestTrinitySampleData (4 failures, 0 errors)</h2>
        <ul>
                <li><a class="failed" href="#sample_data_tests.TestTrinitySampleData:test_DE_analysis_EdgeR">test_DE_analysis_EdgeR</a></li>
                <li><a class="failed" href="#sample_data_tests.TestTrinitySampleData:test_align_and_estimate_abundance">test_align_and_estimate_abundance</a></li>
                <li><a class="failed" href="#sample_data_tests.TestTrinitySampleData:test_full_edgeR_pipeline">test_full_edgeR_pipeline</a></li>
                <li><a class="success">test_genome_guided</a></li>
                <li><a class="success">test_genome_guided_with_jaccard_clipping</a></li>
                <li><a class="success">test_paired_end_normalization</a></li>
                <li><a class="failed" href="#sample_data_tests.TestTrinitySampleData:test_trinity_assembly">test_trinity_assembly</a></li>
        </ul>
    </section>
    <section>
        <h2>test_prep.TestTrinityPrepFlag (0 failures, 0 errors)</h2>
        <ul>
                <li><a class="success">test_fasta</a></li>
                <li><a class="success">test_fasta_gz</a></li>
                <li><a class="success">test_fasta_gz_paired</a></li>
                <li><a class="success">test_fasta_multiple_files_paired</a></li>
                <li><a class="success">test_fasta_multiple_files_single</a></li>
                <li><a class="success">test_fasta_multiple_files_single_reverse</a></li>
                <li><a class="success">test_fasta_paired</a></li>
                <li><a class="success">test_fastq</a></li>
                <li><a class="success">test_fastq_bz2</a></li>
                <li><a class="success">test_fastq_gz</a></li>
                <li><a class="success">test_fastq_multiple_files_paired</a></li>
                <li><a class="success">test_fastq_multiple_files_paired_reverse</a></li>
                <li><a class="success">test_fastq_multiple_files_single</a></li>
                <li><a class="success">test_fastq_multiple_files_single_bz2</a></li>
                <li><a class="success">test_fastq_multiple_files_single_reverse</a></li>
                <li><a class="success">test_paired_fastq</a></li>
                <li><a class="success">test_paired_fastq_gz</a></li>
                <li><a class="success">test_paired_sequences_have_1_or_2_extension</a></li>
        </ul>
    </section>
    <section>
        <h2>tests.TestTrinity (5 failures, 1 errors)</h2>
        <ul>
                <li><a class="failed" href="#tests.TestTrinity:test_Inchworm_handles_compressed_files">test_Inchworm_handles_compressed_files</a></li>
                <li><a class="failed" href="#tests.TestTrinity:test_QuantifyGraph_works">test_QuantifyGraph_works</a></li>
                <li><a class="success">test_cite</a></li>
                <li><a class="success">test_cleanup_removes_temp_files</a></li>
                <li><a class="success">test_invalid_option_error</a></li>
                <li><a class="failed" href="#tests.TestTrinity:test_no_JM_specified_error">test_no_JM_specified_error</a></li>
                <li><a class="success">test_no_bowtie</a></li>
                <li><a class="success">test_no_cleanup_leaves_temp_files</a></li>
                <li><a class="success">test_no_distributed_trinity_exec</a></li>
                <li><a class="success">test_no_run_chrysalis</a></li>
                <li><a class="success">test_no_run_inchworm</a></li>
                <li><a class="success">test_output_correctly_changes_dir</a></li>
                <li><a class="success">test_sample_data_seq_count</a></li>
                <li><a class="success">test_sample_data_trimmed_and_normalized</a></li>
                <li><a class="failed" href="#tests.TestTrinity:test_scaffold_iworm_contigs">test_scaffold_iworm_contigs</a></li>
                <li><a class="failed" href="#tests.TestTrinity:test_set_no_cleanup_and_full_cleanup_error">test_set_no_cleanup_and_full_cleanup_error</a></li>
                <li><a class="success">test_show_full_usage_info</a></li>
                <li><a class="success">test_single_end_with_fa_and_reverse</a></li>
                <li><a class="success">test_single_end_with_fq</a></li>
                <li><a class="success">test_single_end_with_rf_lib_type_error</a></li>
                <li><a class="failed" href="#tests.TestTrinity:test_version">test_version</a></li>
        </ul>
    </section>
</body>
<script>
    Array.prototype.forEach.call(document.querySelectorAll('h1, h2, h3, h4'), function(el) {
        el.addEventListener('click', function() {
            el.nextElementSibling.style.display = document.defaultView.getComputedStyle(el.nextElementSibling).display == 'none' ? 'block' : 'none';
        })
    })
</script>
</html>